# Generated by Django 5.2.14 on 2026-05-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_analysissession_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="black_player",
        ),
        migrations.RemoveField(
            model_name="game",
            name="board_size",
        ),
        migrations.RemoveField(
            model_name="game",
            name="komi",
        ),
        migrations.RemoveField(
            model_name="game",
            name="moves",
        ),
        migrations.RemoveField(
            model_name="game",
            name="white_player",
        ),
        migrations.RemoveField(
            model_name="game",
            name="winner",
        ),
        migrations.AddField(
            model_name="game",
            name="game_data",
            field=models.JSONField(default=dict),
        ),
    ]
