# Generated by Django 5.2.14 on 2026-05-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_game_black_player_remove_game_board_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="source",
            field=models.CharField(
                choices=[
                    ("file", "File"),
                    ("sample", "Sample"),
                    ("live", "Live"),
                    ("none", "None"),
                ],
                max_length=10,
            ),
        ),
    ]
