name: DEPLOY
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: rsync deployments
              uses: burnett01/rsync-deployments@7.1.0
              with:
                  switches: -avzr --delete --exclude=".git"
                  path: ./
                  remote_path: /opt/katago/app/
                  remote_host: ${{ secrets.EC2_HOST }}
                  remote_user: ${{ secrets.EC2_USER }}
                  remote_key: ${{ secrets.EC2_KEY }}
